/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_niu_testjni_NativeClass */

#ifndef _Included_com_niu_testjni_NativeClass
#define _Included_com_niu_testjni_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_niu_testjni_NativeClass
 * Method:    jniArrayAdd
 * Signature: ([II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_niu_testjni_NativeClass_jniArrayAdd
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     com_niu_testjni_NativeClass
 * Method:    jniArrayMul
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_niu_testjni_NativeClass_jniArrayMul
  (JNIEnv *, jclass, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
